name: greeting
on:
  issues:
    types: [opened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "xzf0587/vscode-github-triage-actions"
          ref: main
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Run Greeting 
        uses: ./actions/greeting
        with:
          issue-message: "hello, this is an auto greeting comment."  
          token: ${{secrets.TEAMSFX_BOT}}
