name: Greeting

on: [issues]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "# Message with markdown.\nThis is the message that will be displayed on users' first issue."
          pr-message: "Message that will be displayed on users' first pr. Look, a `code block` for markdown."
