name: Create Milestone For MS DevOps

on: 
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: engineering
    permissions:
      issues: write
      id-token: write
      contents: read
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 335a8848-d80e-4963-93c7-a471d627936f
          tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
          subscription-id: e24d88be-b95f-4815-ba25-ae48defc8da2
  
      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd

      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github action repository
        uses: actions/checkout@v3
        with:
         repository: "microsoft/vscode-github-triage-actions"
         ref: stable 
         path: ./action-base

      - name: Copy action
        run: cp -r .github/actions/create-milestone ./action-base/create-milestone

      - name: Npm install dependencies
        run: npm install azure-devops-node-api --prefix ./action-base
      - name: Npm install
        run: npm install --production --prefix ./action-base
      - name: Build action
        continue-on-error: true
        run: npm run build --prefix ./action-base

      - name: Run Create Milestone
        uses: ./action-base/create-milestone
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          devops-org: "msazure"
          devops-projectId: "Microsoft Teams Extensibility"