name: Create Milestone2222

on: 
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      issues: write
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ef8a04ab-eae0-4524-9fcb-222a2006116c
          tenant-id: 5ee8f0b5-8bde-431b-9cd5-0d27114bf06d
          subscription-id: 2126a3a6-8459-4906-a80d-26b0053f18f4
  
      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd

      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout github action repository
        uses: actions/checkout@v3
        with:
         repository: "microsoft/vscode-github-triage-actions"
         ref: stable 
         path: ./action-base

      - name: Copy action
        run: cp -r .github/actions/create-milestone ./action-base/create-milestone

      - name: Npm install dependencies
        run: npm install azure-devops-node-api --prefix ./action-base
      - name: Npm install
        run: npm install --production --prefix ./action-base
      - name: Build action
        continue-on-error: true
        run: npm run build --prefix ./action-base

      - name: Run Create Milestone
        uses: ./action-base/create-milestone
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          devops-org: "xzf0442"
          devops-projectId: "Test"